import { type ThemePreset, type AppBrandingRecord } from "./branding-types";

export const DEFAULT_BRANDING: AppBrandingRecord = {
  tenant_id: "default",
  app_name: "PARTIU",
  company_name: "PARTIU Mobilidade Urbana",
  primary_color: "#003366",
  secondary_color: "#0088FF",
  accent_color: "#00C6FF",
  background_color: "#0B132B",
  surface_color: "#1C2541",
  text_primary: "#FFFFFF",
  text_secondary: "#94A3B8",
  logo_url: "/favicon.svg",
  splash_logo_url: "/favicon.svg",
  favicon_url: "/favicon.svg",
  header_gradient_start: "#0A2342",
  header_gradient_end: "#00529B",
  footer_sync_with_header: true,
  footer_gradient_start: "#0A2342",
  footer_gradient_end: "#00529B",
  border_radius: "16px",
  font_family: "Plus Jakarta Sans",
};

export const BRANDING_PRESETS: ThemePreset[] = [
  {
    id: "preset-azul-tech",
    name: "Azul Tech (Padrão Oficial)",
    description: "Identidade refinada de alta confiança, segurança e mobilidade moderna.",
    previewColors: {
      primary: "#003366",
      secondary: "#0088FF",
      accent: "#00C6FF",
      gradientStart: "#0A2342",
      gradientEnd: "#00529B",
    },
    branding: {
      tenant_id: "default",
      app_name: "PARTIU",
      company_name: "PARTIU Mobilidade Urbana",
      primary_color: "#003366",
      secondary_color: "#0088FF",
      accent_color: "#00C6FF",
      background_color: "#0B132B",
      surface_color: "#1C2541",
      text_primary: "#FFFFFF",
      text_secondary: "#94A3B8",
      logo_url: "/favicon.svg",
      splash_logo_url: "/favicon.svg",
      favicon_url: "/favicon.svg",
      header_gradient_start: "#0A2342",
      header_gradient_end: "#00529B",
      border_radius: "16px",
      font_family: "Plus Jakarta Sans",
    },
  },
  {
    id: "preset-verde-mobilidade",
    name: "Verde Mobilidade",
    description: "Sustentabilidade urbana, energia limpa e conectividade vibrante.",
    previewColors: {
      primary: "#059669",
      secondary: "#10B981",
      accent: "#34D399",
      gradientStart: "#064E3B",
      gradientEnd: "#059669",
    },
    branding: {
      tenant_id: "default",
      app_name: "PARTIU Verde",
      company_name: "EcoMobilidade Urbana",
      primary_color: "#059669",
      secondary_color: "#10B981",
      accent_color: "#34D399",
      background_color: "#064E3B",
      surface_color: "#065F46",
      text_primary: "#FFFFFF",
      text_secondary: "#A7F3D0",
      logo_url: "/favicon.svg",
      splash_logo_url: "/favicon.svg",
      favicon_url: "/favicon.svg",
      header_gradient_start: "#064E3B",
      header_gradient_end: "#059669",
      border_radius: "18px",
      font_family: "Nunito",
    },
  },
  {
    id: "preset-roxo-premium",
    name: "Roxo Premium",
    description: "Sofisticação de ponta, design fintech e elegância metropolitana.",
    previewColors: {
      primary: "#6D28D9",
      secondary: "#8B5CF6",
      accent: "#A78BFA",
      gradientStart: "#3B0764",
      gradientEnd: "#6D28D9",
    },
    branding: {
      tenant_id: "default",
      app_name: "PARTIU VIP",
      company_name: "Partiu Premium Mobility",
      primary_color: "#6D28D9",
      secondary_color: "#8B5CF6",
      accent_color: "#A78BFA",
      background_color: "#2E1065",
      surface_color: "#3B0764",
      text_primary: "#FFFFFF",
      text_secondary: "#DDD6FE",
      logo_url: "/favicon.svg",
      splash_logo_url: "/favicon.svg",
      favicon_url: "/favicon.svg",
      header_gradient_start: "#3B0764",
      header_gradient_end: "#6D28D9",
      border_radius: "20px",
      font_family: "Montserrat",
    },
  },
  {
    id: "preset-vermelho-executivo",
    name: "Vermelho Executivo",
    description: "Velocidade expressa, alta energia operacional e entregas ultra rápidas.",
    previewColors: {
      primary: "#DC2626",
      secondary: "#EF4444",
      accent: "#F87171",
      gradientStart: "#7F1D1D",
      gradientEnd: "#DC2626",
    },
    branding: {
      tenant_id: "default",
      app_name: "PARTIU Flash",
      company_name: "Partiu Express Mobilidade",
      primary_color: "#DC2626",
      secondary_color: "#EF4444",
      accent_color: "#F87171",
      background_color: "#450A0A",
      surface_color: "#7F1D1D",
      text_primary: "#FFFFFF",
      text_secondary: "#FECACA",
      logo_url: "/favicon.svg",
      splash_logo_url: "/favicon.svg",
      favicon_url: "/favicon.svg",
      header_gradient_start: "#7F1D1D",
      header_gradient_end: "#DC2626",
      border_radius: "16px",
      font_family: "Inter",
    },
  },
  {
    id: "preset-preto-luxo",
    name: "Preto Luxo (Obsidian)",
    description: "Minimalismo extremo nível Uber Black / Stripe com contraste máximo.",
    previewColors: {
      primary: "#0A0A0A",
      secondary: "#27272A",
      accent: "#3B82F6",
      gradientStart: "#000000",
      gradientEnd: "#18181B",
    },
    branding: {
      tenant_id: "default",
      app_name: "PARTIU Black",
      company_name: "Partiu Black Transportation",
      primary_color: "#0A0A0A",
      secondary_color: "#27272A",
      accent_color: "#3B82F6",
      background_color: "#09090B",
      surface_color: "#18181B",
      text_primary: "#F8FAFC",
      text_secondary: "#71717A",
      logo_url: "/favicon.svg",
      splash_logo_url: "/favicon.svg",
      favicon_url: "/favicon.svg",
      header_gradient_start: "#000000",
      header_gradient_end: "#18181B",
      border_radius: "14px",
      font_family: "Inter",
    },
  },
];
