/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CadastroGratuidadeRouteImport } from './routes/cadastro-gratuidade'
import { Route as CadastroMotoristaRouteImport } from './routes/cadastro-motorista'
import { Route as CadastroPassageiroRouteImport } from './routes/cadastro-passageiro'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as EscolherTipoCadastroRouteImport } from './routes/escolher-tipo-cadastro'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppBilhetesRouteImport } from './routes/app.bilhetes'
import { Route as AppDemandaRouteImport } from './routes/app.demanda'
import { Route as AppEncomendasRouteImport } from './routes/app.encomendas'
import { Route as AppLinhasRouteImport } from './routes/app.linhas'
import { Route as AppMotoristaRouteImport } from './routes/app.motorista'
import { Route as AppPasseUniversitarioRouteImport } from './routes/app.passe-universitario'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppRotaRouteImport } from './routes/app.rota'
import { Route as AppShopRouteImport } from './routes/app.shop'
import { Route as AppShopVideosRouteImport } from './routes/app.shop-videos'
import { Route as AppSosRouteImport } from './routes/app.sos'
import { Route as AppViagemRouteImport } from './routes/app.viagem'
import { Route as AppViagensRouteImport } from './routes/app.viagens'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppAdminAfiliadosRouteImport } from './routes/app.admin.afiliados'
import { Route as AppAdminAprovacoesRouteImport } from './routes/app.admin.aprovacoes'
import { Route as AppAdminBannersRouteImport } from './routes/app.admin.banners'
import { Route as AppAdminCaixaRouteImport } from './routes/app.admin.caixa'
import { Route as AppAdminConfiguracoesRouteImport } from './routes/app.admin.configuracoes'
import { Route as AppAdminDespachoRouteImport } from './routes/app.admin.despacho'
import { Route as AppAdminFinanceiroRouteImport } from './routes/app.admin.financeiro'
import { Route as AppAdminFrotaRouteImport } from './routes/app.admin.frota'
import { Route as AppAdminHistoricoRouteImport } from './routes/app.admin.historico'
import { Route as AppAdminLinhasRouteImport } from './routes/app.admin.linhas'
import { Route as AppAdminLocaisRouteImport } from './routes/app.admin.locais'
import { Route as AppAdminLoginRouteImport } from './routes/app.admin.login'
import { Route as AppAdminMonitoramentoRouteImport } from './routes/app.admin.monitoramento'
import { Route as AppAdminMotoristasRouteImport } from './routes/app.admin.motoristas'
import { Route as AppAdminNotificacoesRouteImport } from './routes/app.admin.notificacoes'
import { Route as AppAdminPassageirosRouteImport } from './routes/app.admin.passageiros'
import { Route as AppAdminPontosRouteImport } from './routes/app.admin.pontos'
import { Route as AppAdminRotaRouteImport } from './routes/app.admin.rota'
import { Route as AppAdminSosRouteImport } from './routes/app.admin.sos'
import { Route as AppAdminVeiculoRouteImport } from './routes/app.admin.veiculo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroGratuidadeRoute = CadastroGratuidadeRouteImport.update({
  id: '/cadastro-gratuidade',
  path: '/cadastro-gratuidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroMotoristaRoute = CadastroMotoristaRouteImport.update({
  id: '/cadastro-motorista',
  path: '/cadastro-motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroPassageiroRoute = CadastroPassageiroRouteImport.update({
  id: '/cadastro-passageiro',
  path: '/cadastro-passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolherTipoCadastroRoute = EscolherTipoCadastroRouteImport.update({
  id: '/escolher-tipo-cadastro',
  path: '/escolher-tipo-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppBilhetesRoute = AppBilhetesRouteImport.update({
  id: '/bilhetes',
  path: '/bilhetes',
  getParentRoute: () => AppRoute,
} as any)
const AppDemandaRoute = AppDemandaRouteImport.update({
  id: '/demanda',
  path: '/demanda',
  getParentRoute: () => AppRoute,
} as any)
const AppEncomendasRoute = AppEncomendasRouteImport.update({
  id: '/encomendas',
  path: '/encomendas',
  getParentRoute: () => AppRoute,
} as any)
const AppLinhasRoute = AppLinhasRouteImport.update({
  id: '/linhas',
  path: '/linhas',
  getParentRoute: () => AppRoute,
} as any)
const AppMotoristaRoute = AppMotoristaRouteImport.update({
  id: '/motorista',
  path: '/motorista',
  getParentRoute: () => AppRoute,
} as any)
const AppPasseUniversitarioRoute = AppPasseUniversitarioRouteImport.update({
  id: '/passe-universitario',
  path: '/passe-universitario',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppRotaRoute = AppRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AppRoute,
} as any)
const AppShopRoute = AppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AppRoute,
} as any)
const AppShopVideosRoute = AppShopVideosRouteImport.update({
  id: '/shop-videos',
  path: '/shop-videos',
  getParentRoute: () => AppRoute,
} as any)
const AppSosRoute = AppSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AppRoute,
} as any)
const AppViagemRoute = AppViagemRouteImport.update({
  id: '/viagem',
  path: '/viagem',
  getParentRoute: () => AppRoute,
} as any)
const AppViagensRoute = AppViagensRouteImport.update({
  id: '/viagens',
  path: '/viagens',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAfiliadosRoute = AppAdminAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAprovacoesRoute = AppAdminAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminBannersRoute = AppAdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCaixaRoute = AppAdminCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminConfiguracoesRoute = AppAdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminDespachoRoute = AppAdminDespachoRouteImport.update({
  id: '/despacho',
  path: '/despacho',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFinanceiroRoute = AppAdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFrotaRoute = AppAdminFrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHistoricoRoute = AppAdminHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLinhasRoute = AppAdminLinhasRouteImport.update({
  id: '/linhas',
  path: '/linhas',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLocaisRoute = AppAdminLocaisRouteImport.update({
  id: '/locais',
  path: '/locais',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLoginRoute = AppAdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMonitoramentoRoute = AppAdminMonitoramentoRouteImport.update({
  id: '/monitoramento',
  path: '/monitoramento',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMotoristasRoute = AppAdminMotoristasRouteImport.update({
  id: '/motoristas',
  path: '/motoristas',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminNotificacoesRoute = AppAdminNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPassageirosRoute = AppAdminPassageirosRouteImport.update({
  id: '/passageiros',
  path: '/passageiros',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPontosRoute = AppAdminPontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRotaRoute = AppAdminRotaRouteImport.update({
  id: '/rota',
  path: '/rota',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSosRoute = AppAdminSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminVeiculoRoute = AppAdminVeiculoRouteImport.update({
  id: '/veiculo',
  path: '/veiculo',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro-gratuidade': typeof CadastroGratuidadeRoute
  '/cadastro-motorista': typeof CadastroMotoristaRoute
  '/cadastro-passageiro': typeof CadastroPassageiroRoute
  '/design-system': typeof DesignSystemRoute
  '/escolher-tipo-cadastro': typeof EscolherTipoCadastroRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/bilhetes': typeof AppBilhetesRoute
  '/app/demanda': typeof AppDemandaRoute
  '/app/encomendas': typeof AppEncomendasRoute
  '/app/linhas': typeof AppLinhasRoute
  '/app/motorista': typeof AppMotoristaRoute
  '/app/passe-universitario': typeof AppPasseUniversitarioRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/rota': typeof AppRotaRoute
  '/app/shop': typeof AppShopRoute
  '/app/shop-videos': typeof AppShopVideosRoute
  '/app/sos': typeof AppSosRoute
  '/app/viagem': typeof AppViagemRoute
  '/app/viagens': typeof AppViagensRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/afiliados': typeof AppAdminAfiliadosRoute
  '/app/admin/aprovacoes': typeof AppAdminAprovacoesRoute
  '/app/admin/banners': typeof AppAdminBannersRoute
  '/app/admin/caixa': typeof AppAdminCaixaRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/despacho': typeof AppAdminDespachoRoute
  '/app/admin/financeiro': typeof AppAdminFinanceiroRoute
  '/app/admin/frota': typeof AppAdminFrotaRoute
  '/app/admin/historico': typeof AppAdminHistoricoRoute
  '/app/admin/linhas': typeof AppAdminLinhasRoute
  '/app/admin/locais': typeof AppAdminLocaisRoute
  '/app/admin/login': typeof AppAdminLoginRoute
  '/app/admin/monitoramento': typeof AppAdminMonitoramentoRoute
  '/app/admin/motoristas': typeof AppAdminMotoristasRoute
  '/app/admin/notificacoes': typeof AppAdminNotificacoesRoute
  '/app/admin/passageiros': typeof AppAdminPassageirosRoute
  '/app/admin/pontos': typeof AppAdminPontosRoute
  '/app/admin/rota': typeof AppAdminRotaRoute
  '/app/admin/sos': typeof AppAdminSosRoute
  '/app/admin/veiculo': typeof AppAdminVeiculoRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro-gratuidade': typeof CadastroGratuidadeRoute
  '/cadastro-motorista': typeof CadastroMotoristaRoute
  '/cadastro-passageiro': typeof CadastroPassageiroRoute
  '/design-system': typeof DesignSystemRoute
  '/escolher-tipo-cadastro': typeof EscolherTipoCadastroRoute
  '/app/bilhetes': typeof AppBilhetesRoute
  '/app/demanda': typeof AppDemandaRoute
  '/app/encomendas': typeof AppEncomendasRoute
  '/app/linhas': typeof AppLinhasRoute
  '/app/motorista': typeof AppMotoristaRoute
  '/app/passe-universitario': typeof AppPasseUniversitarioRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/rota': typeof AppRotaRoute
  '/app/shop': typeof AppShopRoute
  '/app/shop-videos': typeof AppShopVideosRoute
  '/app/sos': typeof AppSosRoute
  '/app/viagem': typeof AppViagemRoute
  '/app/viagens': typeof AppViagensRoute
  '/app': typeof AppIndexRoute
  '/app/admin/afiliados': typeof AppAdminAfiliadosRoute
  '/app/admin/aprovacoes': typeof AppAdminAprovacoesRoute
  '/app/admin/banners': typeof AppAdminBannersRoute
  '/app/admin/caixa': typeof AppAdminCaixaRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/despacho': typeof AppAdminDespachoRoute
  '/app/admin/financeiro': typeof AppAdminFinanceiroRoute
  '/app/admin/frota': typeof AppAdminFrotaRoute
  '/app/admin/historico': typeof AppAdminHistoricoRoute
  '/app/admin/linhas': typeof AppAdminLinhasRoute
  '/app/admin/locais': typeof AppAdminLocaisRoute
  '/app/admin/login': typeof AppAdminLoginRoute
  '/app/admin/monitoramento': typeof AppAdminMonitoramentoRoute
  '/app/admin/motoristas': typeof AppAdminMotoristasRoute
  '/app/admin/notificacoes': typeof AppAdminNotificacoesRoute
  '/app/admin/passageiros': typeof AppAdminPassageirosRoute
  '/app/admin/pontos': typeof AppAdminPontosRoute
  '/app/admin/rota': typeof AppAdminRotaRoute
  '/app/admin/sos': typeof AppAdminSosRoute
  '/app/admin/veiculo': typeof AppAdminVeiculoRoute
  '/app/admin': typeof AppAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/cadastro-gratuidade': typeof CadastroGratuidadeRoute
  '/cadastro-motorista': typeof CadastroMotoristaRoute
  '/cadastro-passageiro': typeof CadastroPassageiroRoute
  '/design-system': typeof DesignSystemRoute
  '/escolher-tipo-cadastro': typeof EscolherTipoCadastroRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/bilhetes': typeof AppBilhetesRoute
  '/app/demanda': typeof AppDemandaRoute
  '/app/encomendas': typeof AppEncomendasRoute
  '/app/linhas': typeof AppLinhasRoute
  '/app/motorista': typeof AppMotoristaRoute
  '/app/passe-universitario': typeof AppPasseUniversitarioRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/rota': typeof AppRotaRoute
  '/app/shop': typeof AppShopRoute
  '/app/shop-videos': typeof AppShopVideosRoute
  '/app/sos': typeof AppSosRoute
  '/app/viagem': typeof AppViagemRoute
  '/app/viagens': typeof AppViagensRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/afiliados': typeof AppAdminAfiliadosRoute
  '/app/admin/aprovacoes': typeof AppAdminAprovacoesRoute
  '/app/admin/banners': typeof AppAdminBannersRoute
  '/app/admin/caixa': typeof AppAdminCaixaRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/despacho': typeof AppAdminDespachoRoute
  '/app/admin/financeiro': typeof AppAdminFinanceiroRoute
  '/app/admin/frota': typeof AppAdminFrotaRoute
  '/app/admin/historico': typeof AppAdminHistoricoRoute
  '/app/admin/linhas': typeof AppAdminLinhasRoute
  '/app/admin/locais': typeof AppAdminLocaisRoute
  '/app/admin/login': typeof AppAdminLoginRoute
  '/app/admin/monitoramento': typeof AppAdminMonitoramentoRoute
  '/app/admin/motoristas': typeof AppAdminMotoristasRoute
  '/app/admin/notificacoes': typeof AppAdminNotificacoesRoute
  '/app/admin/passageiros': typeof AppAdminPassageirosRoute
  '/app/admin/pontos': typeof AppAdminPontosRoute
  '/app/admin/rota': typeof AppAdminRotaRoute
  '/app/admin/sos': typeof AppAdminSosRoute
  '/app/admin/veiculo': typeof AppAdminVeiculoRoute
  '/app/admin/': typeof AppAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/cadastro-gratuidade'
    | '/cadastro-motorista'
    | '/cadastro-passageiro'
    | '/design-system'
    | '/escolher-tipo-cadastro'
    | '/app/admin'
    | '/app/bilhetes'
    | '/app/demanda'
    | '/app/encomendas'
    | '/app/linhas'
    | '/app/motorista'
    | '/app/passe-universitario'
    | '/app/perfil'
    | '/app/rota'
    | '/app/shop'
    | '/app/shop-videos'
    | '/app/sos'
    | '/app/viagem'
    | '/app/viagens'
    | '/app/'
    | '/app/admin/afiliados'
    | '/app/admin/aprovacoes'
    | '/app/admin/banners'
    | '/app/admin/caixa'
    | '/app/admin/configuracoes'
    | '/app/admin/despacho'
    | '/app/admin/financeiro'
    | '/app/admin/frota'
    | '/app/admin/historico'
    | '/app/admin/linhas'
    | '/app/admin/locais'
    | '/app/admin/login'
    | '/app/admin/monitoramento'
    | '/app/admin/motoristas'
    | '/app/admin/notificacoes'
    | '/app/admin/passageiros'
    | '/app/admin/pontos'
    | '/app/admin/rota'
    | '/app/admin/sos'
    | '/app/admin/veiculo'
    | '/app/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro-gratuidade'
    | '/cadastro-motorista'
    | '/cadastro-passageiro'
    | '/design-system'
    | '/escolher-tipo-cadastro'
    | '/app/bilhetes'
    | '/app/demanda'
    | '/app/encomendas'
    | '/app/linhas'
    | '/app/motorista'
    | '/app/passe-universitario'
    | '/app/perfil'
    | '/app/rota'
    | '/app/shop'
    | '/app/shop-videos'
    | '/app/sos'
    | '/app/viagem'
    | '/app/viagens'
    | '/app'
    | '/app/admin/afiliados'
    | '/app/admin/aprovacoes'
    | '/app/admin/banners'
    | '/app/admin/caixa'
    | '/app/admin/configuracoes'
    | '/app/admin/despacho'
    | '/app/admin/financeiro'
    | '/app/admin/frota'
    | '/app/admin/historico'
    | '/app/admin/linhas'
    | '/app/admin/locais'
    | '/app/admin/login'
    | '/app/admin/monitoramento'
    | '/app/admin/motoristas'
    | '/app/admin/notificacoes'
    | '/app/admin/passageiros'
    | '/app/admin/pontos'
    | '/app/admin/rota'
    | '/app/admin/sos'
    | '/app/admin/veiculo'
    | '/app/admin'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/cadastro-gratuidade'
    | '/cadastro-motorista'
    | '/cadastro-passageiro'
    | '/design-system'
    | '/escolher-tipo-cadastro'
    | '/app/admin'
    | '/app/bilhetes'
    | '/app/demanda'
    | '/app/encomendas'
    | '/app/linhas'
    | '/app/motorista'
    | '/app/passe-universitario'
    | '/app/perfil'
    | '/app/rota'
    | '/app/shop'
    | '/app/shop-videos'
    | '/app/sos'
    | '/app/viagem'
    | '/app/viagens'
    | '/app/'
    | '/app/admin/afiliados'
    | '/app/admin/aprovacoes'
    | '/app/admin/banners'
    | '/app/admin/caixa'
    | '/app/admin/configuracoes'
    | '/app/admin/despacho'
    | '/app/admin/financeiro'
    | '/app/admin/frota'
    | '/app/admin/historico'
    | '/app/admin/linhas'
    | '/app/admin/locais'
    | '/app/admin/login'
    | '/app/admin/monitoramento'
    | '/app/admin/motoristas'
    | '/app/admin/notificacoes'
    | '/app/admin/passageiros'
    | '/app/admin/pontos'
    | '/app/admin/rota'
    | '/app/admin/sos'
    | '/app/admin/veiculo'
    | '/app/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CadastroGratuidadeRoute: typeof CadastroGratuidadeRoute
  CadastroMotoristaRoute: typeof CadastroMotoristaRoute
  CadastroPassageiroRoute: typeof CadastroPassageiroRoute
  DesignSystemRoute: typeof DesignSystemRoute
  EscolherTipoCadastroRoute: typeof EscolherTipoCadastroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-gratuidade': {
      id: '/cadastro-gratuidade'
      path: '/cadastro-gratuidade'
      fullPath: '/cadastro-gratuidade'
      preLoaderRoute: typeof CadastroGratuidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-motorista': {
      id: '/cadastro-motorista'
      path: '/cadastro-motorista'
      fullPath: '/cadastro-motorista'
      preLoaderRoute: typeof CadastroMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-passageiro': {
      id: '/cadastro-passageiro'
      path: '/cadastro-passageiro'
      fullPath: '/cadastro-passageiro'
      preLoaderRoute: typeof CadastroPassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolher-tipo-cadastro': {
      id: '/escolher-tipo-cadastro'
      path: '/escolher-tipo-cadastro'
      fullPath: '/escolher-tipo-cadastro'
      preLoaderRoute: typeof EscolherTipoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bilhetes': {
      id: '/app/bilhetes'
      path: '/bilhetes'
      fullPath: '/app/bilhetes'
      preLoaderRoute: typeof AppBilhetesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/demanda': {
      id: '/app/demanda'
      path: '/demanda'
      fullPath: '/app/demanda'
      preLoaderRoute: typeof AppDemandaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/encomendas': {
      id: '/app/encomendas'
      path: '/encomendas'
      fullPath: '/app/encomendas'
      preLoaderRoute: typeof AppEncomendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/linhas': {
      id: '/app/linhas'
      path: '/linhas'
      fullPath: '/app/linhas'
      preLoaderRoute: typeof AppLinhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/motorista': {
      id: '/app/motorista'
      path: '/motorista'
      fullPath: '/app/motorista'
      preLoaderRoute: typeof AppMotoristaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/passe-universitario': {
      id: '/app/passe-universitario'
      path: '/passe-universitario'
      fullPath: '/app/passe-universitario'
      preLoaderRoute: typeof AppPasseUniversitarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rota': {
      id: '/app/rota'
      path: '/rota'
      fullPath: '/app/rota'
      preLoaderRoute: typeof AppRotaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop': {
      id: '/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AppShopRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shop-videos': {
      id: '/app/shop-videos'
      path: '/shop-videos'
      fullPath: '/app/shop-videos'
      preLoaderRoute: typeof AppShopVideosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sos': {
      id: '/app/sos'
      path: '/sos'
      fullPath: '/app/sos'
      preLoaderRoute: typeof AppSosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/viagem': {
      id: '/app/viagem'
      path: '/viagem'
      fullPath: '/app/viagem'
      preLoaderRoute: typeof AppViagemRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/viagens': {
      id: '/app/viagens'
      path: '/viagens'
      fullPath: '/app/viagens'
      preLoaderRoute: typeof AppViagensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/afiliados': {
      id: '/app/admin/afiliados'
      path: '/afiliados'
      fullPath: '/app/admin/afiliados'
      preLoaderRoute: typeof AppAdminAfiliadosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/aprovacoes': {
      id: '/app/admin/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/app/admin/aprovacoes'
      preLoaderRoute: typeof AppAdminAprovacoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/banners': {
      id: '/app/admin/banners'
      path: '/banners'
      fullPath: '/app/admin/banners'
      preLoaderRoute: typeof AppAdminBannersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/caixa': {
      id: '/app/admin/caixa'
      path: '/caixa'
      fullPath: '/app/admin/caixa'
      preLoaderRoute: typeof AppAdminCaixaRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/configuracoes': {
      id: '/app/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/admin/configuracoes'
      preLoaderRoute: typeof AppAdminConfiguracoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/despacho': {
      id: '/app/admin/despacho'
      path: '/despacho'
      fullPath: '/app/admin/despacho'
      preLoaderRoute: typeof AppAdminDespachoRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/financeiro': {
      id: '/app/admin/financeiro'
      path: '/financeiro'
      fullPath: '/app/admin/financeiro'
      preLoaderRoute: typeof AppAdminFinanceiroRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/frota': {
      id: '/app/admin/frota'
      path: '/frota'
      fullPath: '/app/admin/frota'
      preLoaderRoute: typeof AppAdminFrotaRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/historico': {
      id: '/app/admin/historico'
      path: '/historico'
      fullPath: '/app/admin/historico'
      preLoaderRoute: typeof AppAdminHistoricoRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/linhas': {
      id: '/app/admin/linhas'
      path: '/linhas'
      fullPath: '/app/admin/linhas'
      preLoaderRoute: typeof AppAdminLinhasRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/locais': {
      id: '/app/admin/locais'
      path: '/locais'
      fullPath: '/app/admin/locais'
      preLoaderRoute: typeof AppAdminLocaisRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/login': {
      id: '/app/admin/login'
      path: '/login'
      fullPath: '/app/admin/login'
      preLoaderRoute: typeof AppAdminLoginRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/monitoramento': {
      id: '/app/admin/monitoramento'
      path: '/monitoramento'
      fullPath: '/app/admin/monitoramento'
      preLoaderRoute: typeof AppAdminMonitoramentoRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/motoristas': {
      id: '/app/admin/motoristas'
      path: '/motoristas'
      fullPath: '/app/admin/motoristas'
      preLoaderRoute: typeof AppAdminMotoristasRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/notificacoes': {
      id: '/app/admin/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/admin/notificacoes'
      preLoaderRoute: typeof AppAdminNotificacoesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/passageiros': {
      id: '/app/admin/passageiros'
      path: '/passageiros'
      fullPath: '/app/admin/passageiros'
      preLoaderRoute: typeof AppAdminPassageirosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/pontos': {
      id: '/app/admin/pontos'
      path: '/pontos'
      fullPath: '/app/admin/pontos'
      preLoaderRoute: typeof AppAdminPontosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/rota': {
      id: '/app/admin/rota'
      path: '/rota'
      fullPath: '/app/admin/rota'
      preLoaderRoute: typeof AppAdminRotaRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/sos': {
      id: '/app/admin/sos'
      path: '/sos'
      fullPath: '/app/admin/sos'
      preLoaderRoute: typeof AppAdminSosRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/veiculo': {
      id: '/app/admin/veiculo'
      path: '/veiculo'
      fullPath: '/app/admin/veiculo'
      preLoaderRoute: typeof AppAdminVeiculoRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAfiliadosRoute: typeof AppAdminAfiliadosRoute
  AppAdminAprovacoesRoute: typeof AppAdminAprovacoesRoute
  AppAdminBannersRoute: typeof AppAdminBannersRoute
  AppAdminCaixaRoute: typeof AppAdminCaixaRoute
  AppAdminConfiguracoesRoute: typeof AppAdminConfiguracoesRoute
  AppAdminDespachoRoute: typeof AppAdminDespachoRoute
  AppAdminFinanceiroRoute: typeof AppAdminFinanceiroRoute
  AppAdminFrotaRoute: typeof AppAdminFrotaRoute
  AppAdminHistoricoRoute: typeof AppAdminHistoricoRoute
  AppAdminLinhasRoute: typeof AppAdminLinhasRoute
  AppAdminLocaisRoute: typeof AppAdminLocaisRoute
  AppAdminLoginRoute: typeof AppAdminLoginRoute
  AppAdminMonitoramentoRoute: typeof AppAdminMonitoramentoRoute
  AppAdminMotoristasRoute: typeof AppAdminMotoristasRoute
  AppAdminNotificacoesRoute: typeof AppAdminNotificacoesRoute
  AppAdminPassageirosRoute: typeof AppAdminPassageirosRoute
  AppAdminPontosRoute: typeof AppAdminPontosRoute
  AppAdminRotaRoute: typeof AppAdminRotaRoute
  AppAdminSosRoute: typeof AppAdminSosRoute
  AppAdminVeiculoRoute: typeof AppAdminVeiculoRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAfiliadosRoute: AppAdminAfiliadosRoute,
  AppAdminAprovacoesRoute: AppAdminAprovacoesRoute,
  AppAdminBannersRoute: AppAdminBannersRoute,
  AppAdminCaixaRoute: AppAdminCaixaRoute,
  AppAdminConfiguracoesRoute: AppAdminConfiguracoesRoute,
  AppAdminDespachoRoute: AppAdminDespachoRoute,
  AppAdminFinanceiroRoute: AppAdminFinanceiroRoute,
  AppAdminFrotaRoute: AppAdminFrotaRoute,
  AppAdminHistoricoRoute: AppAdminHistoricoRoute,
  AppAdminLinhasRoute: AppAdminLinhasRoute,
  AppAdminLocaisRoute: AppAdminLocaisRoute,
  AppAdminLoginRoute: AppAdminLoginRoute,
  AppAdminMonitoramentoRoute: AppAdminMonitoramentoRoute,
  AppAdminMotoristasRoute: AppAdminMotoristasRoute,
  AppAdminNotificacoesRoute: AppAdminNotificacoesRoute,
  AppAdminPassageirosRoute: AppAdminPassageirosRoute,
  AppAdminPontosRoute: AppAdminPontosRoute,
  AppAdminRotaRoute: AppAdminRotaRoute,
  AppAdminSosRoute: AppAdminSosRoute,
  AppAdminVeiculoRoute: AppAdminVeiculoRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppBilhetesRoute: typeof AppBilhetesRoute
  AppDemandaRoute: typeof AppDemandaRoute
  AppEncomendasRoute: typeof AppEncomendasRoute
  AppLinhasRoute: typeof AppLinhasRoute
  AppMotoristaRoute: typeof AppMotoristaRoute
  AppPasseUniversitarioRoute: typeof AppPasseUniversitarioRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppRotaRoute: typeof AppRotaRoute
  AppShopRoute: typeof AppShopRoute
  AppShopVideosRoute: typeof AppShopVideosRoute
  AppSosRoute: typeof AppSosRoute
  AppViagemRoute: typeof AppViagemRoute
  AppViagensRoute: typeof AppViagensRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppBilhetesRoute: AppBilhetesRoute,
  AppDemandaRoute: AppDemandaRoute,
  AppEncomendasRoute: AppEncomendasRoute,
  AppLinhasRoute: AppLinhasRoute,
  AppMotoristaRoute: AppMotoristaRoute,
  AppPasseUniversitarioRoute: AppPasseUniversitarioRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppRotaRoute: AppRotaRoute,
  AppShopRoute: AppShopRoute,
  AppShopVideosRoute: AppShopVideosRoute,
  AppSosRoute: AppSosRoute,
  AppViagemRoute: AppViagemRoute,
  AppViagensRoute: AppViagensRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CadastroGratuidadeRoute: CadastroGratuidadeRoute,
  CadastroMotoristaRoute: CadastroMotoristaRoute,
  CadastroPassageiroRoute: CadastroPassageiroRoute,
  DesignSystemRoute: DesignSystemRoute,
  EscolherTipoCadastroRoute: EscolherTipoCadastroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
